# Generated by Django 4.1.5 on 2023-02-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rango", "0002_alter_category_options_category_likes_category_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="1"),
            preserve_default=False,
        ),
    ]
